baseurl = "/"
languageCode = "ko"
defaultContentLanguage = 'kr'
publishDir = "docs"
theme = "terminal"
pagination.pagerSize = 10

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
noClasses = true

[params]
language= "kr"
# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 10

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
# showLastUpdated = true

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# whether to show a page's estimated reading time
readingTime = false # default

# whether to show a table of contents
# can be overridden in a page's front-matter
# 글 상단에 요약 표시하기
# Toc = true

# set title for the table of contents
# can be overridden in a page's front-matter
# TocTitle = "글 목록" # default

# Set date/time format for posts
# This will impact the date/time displayed on
# index.html, the posts list page, and on posts themselves
# This value can also be configured per-post on front matter
# If you have any issues with the timezone rendering differently
# than you expected, please ensure your timezone is correctly set
# on your server.
# This value can be customized according to Hugo documentation:
# https://gohugo.io/functions/time/format/
# Default value (no changes needed):
# dateFormat = "2006-01-02"
# Example format, with date, time, and timezone abbreviation:
# dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
creator = "ciaolee87"
site = "www.d3v-friends.com"

[languages]
[language.kr]
languageName = "Korean"
title = "d3v-friends"


[languages.kr.params]
subtitle = "차오 라이프"
owner = "ciaolee87"
keywords = "dev and life"
copyright = "ciaolee87"
menuMore = "더보기"
readMore = "자세히"
readOtherPosts = "다른글 보기"
newerPosts = "새로운 글"
olderPosts = "예전 글"
missingContentMessage = "페이지를 찾을 수 없습니다."
missingBackButtonLabel = "메인 페이지로 이동"
minuteReadingTime = "분전 작성함"
words = "words"

[languages.kr.params.logo]
logoText = "d3v-friends"
logoHomeLink = "/"


# 메뉴바
[languages.kr.menu]
[[languages.kr.menu.main]]
identifier = "raylib"
name = "raylib"
url = "/archive/raylib"

[[languages.kr.menu.main]]
identifier = "cpp"
name = "cpp"
url = "/archive/cpp"



# 테마 정하기
[module]
[[module.imports]]
path = 'terminal'
